version: "3.6"

services:
  app:
    image: ${APP_NAME}
    container_name: ${APP_NAME}_web
    ports:
      - 3000:3000
    restart: always
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15.1
    container_name: ${APP_NAME}_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${APP_NAME}_mailhog
    ports:
      - '${MAIL_PORT}:1025'
      - '${MAILHOG_DASHBOARD_PORT}:8025'
    
  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: ${APP_NAME}_swagger
    ports:
      - 8080:8080
    environment:
      SWAGGER_JSON: /swagger.json
    volumes:
    - ./swagger/swagger.json:/swagger.json

volumes:
  node_modules:
  postgres:
